name: Build and Deploy Windows Game

on:
  push:
    branches: [main, android-main]
  pull_request:
    branches: [main, android-main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Lua and dependencies
        run: |
          choco install lua
          choco install luarocks
          luarocks install luacheck
          luarocks install luasocket
          luarocks install dkjson

      - name: Add LuaRocks to PATH
        run: |
          echo "C:\Program Files (x86)\LuaRocks\systree\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\tools\luarocks\systree\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\ProgramData\chocolatey\lib\luarocks\tools\luarocks\systree\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "PATH: $env:PATH"
          Get-ChildItem -Path "C:\Program Files (x86)\LuaRocks\systree\bin" -Filter luacheck* -Recurse -ErrorAction SilentlyContinue
          Get-ChildItem -Path "C:\tools\luarocks\systree\bin" -Filter luacheck* -Recurse -ErrorAction SilentlyContinue
          Get-ChildItem -Path "C:\ProgramData\chocolatey\lib\luarocks\tools\luarocks\systree\bin" -Filter luacheck* -Recurse -ErrorAction SilentlyContinue

      - name: Download Love2D for Windows
        run: |
          curl -LO https://github.com/love2d/love/releases/download/11.4/love-11.4-win64.zip
          powershell Expand-Archive -Path love-11.4-win64.zip -DestinationPath .

      - name: Build .love file
        run: |
          powershell Compress-Archive -Path * -DestinationPath game.zip
          ren game.zip game.love

      - name: Create Windows EXE
        run: cmd /c "copy /b love-11.4-win64\love.exe+game.love game.exe"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            game.exe
            game.love
